Fix unable to deploy encryption verticle in docker
- Error log while encyrption verticle deployment -
  ``java.lang.NoClassDefFoundError: Could not initialize class
com.sun.jna.Native``
- Happened because of use of tmpfs
   - libsodium libraries fail to load in Docker when --tmpfs /tmp
     due to "noexec"  flag on /tmp see:
     1. https://github.com/netty/netty-tcnative/issues/264
     2. https://github.com/moby/moby/issues/18853